### ISSUE TITLE
Volume reverts to 100% on each new song in playlist

### ISSUE THREAD

**Issue by karlsluis** [nextbigsoundinc/Tunebot-2.0#4]

**Comment by psi** [comment]
Noted. I looked at this for a few minutes yesterday. I have a hunch as to what's happening, but need to spend a little more time digging.

**Comment by psi** [comment]
Actually, looks like this might be a Mopidy bug...

https://github.com/mopidy/mopidy/issues/886

**Comment by psi** [comment]
But I can't reproduce this on my Mac with Mopidy 1.0.4. The Tunebot machine has an older version of Mopidy. Gonna try upgrading.

**Comment by psi** [comment]
Fixed by upgrading to Mopidy 1.0.4!
